[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
[build]
  publish = "dist"
  command = "vite build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
