name: Build and Deploy Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Connect to Server and Pull Latest Changes
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"

      - name: Cleanup SSH keys
        run: rm -rf ~/.ssh

      - name: Install dependencies
        working-directory: ${{ secrets.WORK_DIR }} # Specifica il percorso dove si trova il progetto
        run: npm install

      - name: Run build
        working-directory: ${{ secrets.WORK_DIR }} # Specifica il percorso dove si trova il progetto
        run: npm run build

      - name: Restart server or services (optional)
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && pm2 restart all || systemctl restart myservice"
