on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Upload build.sh script
        uses: actions/upload-artifact@v3
        with:
          name: build-script
          path: ./build.sh

      - name: Download build.sh script from artifact
        uses: actions/download-artifact@v3
        with:
          name: build-script

      - name: Copy build.sh script to the server
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa build.sh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}

      - name: Execute build.sh script on the server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.WORK_DIR }}
            chmod +x build.sh
           sh ./build.sh
            exit
          EOF

      - name: Cleanup
        run: rm -rf ~/.ssh
